language: node_js

install:
  - bundle install
  - npm install -g bower
  - bower install

before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "HlWyxVvbm5EzW7risMHwGckOT3QOGxTqRlobQgapUMWh4yXBR9ZYpqpk//gJsRPGxNsL6POGrevxcks2YjBaBuC1u76JIPRNiBAWWuJq3fzmQBObUbkLZB4AnLytbu0IHKCHdOf17uqcU+fA2Q4NJJ4p6QCjmUSCAofSPq7XJBM="
  
