language: node_js

install:
  - bundle install
  - npm install -g bower
  - bower install

before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GIT_NAME}:${GH_TOKEN}@github.com" > .git/credentials

script: bundle exec rake site:deploy --quiet

env:
  global:
    # travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
    secure: "cSZ092T9zNyvG9AyQNLoQsuPXblU08r5mhMGnBX+2r5AFVBwRmPEQmg7bmT1gH0AfCpmw9P/OIu7/zii3X+euMcQebOh8V8glwRrbxfP3sU/QYyT8Gcry3VqzNBbTrrAkGRyxw8b+Wm9Dt9KIREV4qifEz4m7xtiNVfvjIp1JQk="
